Korean translation
DiscordSRV/DiscordSRV pull request #1005
Opened 2021-01-30 17:46 UTC by ShapeLayer

2021-01-30 23:06 UTC, Vankka requested changes
You've completely changed the formatting of the Korean files, making them inconsistent with the others,
- There should not be more than one empty line of gap between options
- The comments should be in the same place as the English files, specifically they should not be split for every option
- You've added semicolons (`:`) when breaking a line, this seems quite unconventional

2021-01-31 02:26 UTC, ShapeLayer commented
Oh, I'm sorry very much.
As focusing on Korean translation and obvious meaning, I neglected the original format.
I'll fix it as soon as possible.

2021-02-02 02:56 UTC, ShapeLayer commented
I worked done. Please check the code.

2021-02-02 03:08 UTC, granny approved these changes

2021-02-02 03:13 UTC, merged