pl.yml
DiscordSRV/DiscordSRV pull request #1085
Opened 2021-04-14 19:09 UTC by Zabujca997

Polish version

```
# Minecraft -> Synchronizacja pseudonimów na Discordzie
#
# NicknameSynchronizationEnabled: czy automatycznie ustawić pseudonim użytkownika discorda na format pseudonimu
# NicknameSynchronizationCycleTime: liczba minut między wielokrotnym uruchamianiem synchronizacji dla wszystkich graczy online
# NicknameSynchronizationFormat: format pseudonimu (pamiętaj, że nie powinien przekraczać 32 znaków)
# %displayname%: nazwa wyświetlana gracza
# przykład: Jeb
# %username%: nazwa użytkownika gracza
# przykład: Jeb_
# Symbole zastępcze interfejsu API są obsługiwane dla wartości
#
NicknameSynchronizationEnabled: false
NicknameSynchronizationCycleTime: 3
NicknameSynchronizationFormat: "%displayname%"

# Grupa Minecraft <-> Synchronizacja ról Discord
# Wymaga Vault
#
# GroupRoleSynchronizationGroupsAndRolesToSync: są to role / grupy, które chcesz zsynchronizować między Discord i Minecraft
# {"MC_GROUP_NAME": "DISCORD_ROLE_ID"} to format, który należy zastosować przy dodawaniu większej liczby par grupa / rola
# Aby uzyskać identyfikatory ról swojej gildii Discord, uruchom "/discord debug" i spójrz na pierwszą sekcję
# GroupRoleSynchronizationMinecraftIsAuthoritative: czy zmiany grupowe w Minecrafcie zastępują zmiany ról w Discordzie
# GroupRoleSynchronizationOneWay: czy synchronizować tylko w jedną stronę, sposób synchronizacji zależy od wartości
# of GroupRoleSynchronizationMinecraftIsAuthoritative.
# GroupRoleSynchronizationEnableDenyPermission: czy uprawnienia discordsrv.sync.deny są włączone czy nie.
# GroupRoleSynchronizationPrimaryGroupOnly: jeśli prawda, tylko podstawowa grupa gracza jest liczona do synchronizacji,
# w przeciwnym razie synchronizacja grup liczy wszystkie grupy, w których znajduje się gracz, w tym grupy nadrzędne
# GroupRoleSynchronizationOnLink: czy ponownie synchronizować, gdy gracz łączy się
# GroupRoleSynchronizationCycleTime: liczba minut między wielokrotnym uruchamianiem synchronizacji dla wszystkich graczy online
# GroupRoleSynchronizationCycleCompletely: czy synchronizacje działające na zegarze powinny synchronizować każdego członka w botach Discord Servers
#
GroupRoleSynchronizationGroupsAndRolesToSync: {"trusted": "000000000000000000", "vip": "000000000000000000"}
GroupRoleSynchronizationMinecraftIsAuthoritative: true
GroupRoleSynchronizationOneWay: false
GroupRoleSynchronizationEnableDenyPermission: false
GroupRoleSynchronizationPrimaryGroupOnly: false
GroupRoleSynchronizationOnLink: true
GroupRoleSynchronizationCycleTime: 5
GroupRoleSynchronizationCycleCompletely: false

# synchronizację banów
# Kiedy gracz zostanie zbanowany na serwerze, gdy ma połączone konto Discord, możesz opcjonalnie zablokować go na serwerze Discord i odwrotnie
#
# BanSynchronizationDiscordToMinecraft: czy banować ludzi na serwerze Minecraft, jeśli zostaną zbanowani na serwerze Discord
# BanSynchronizationDiscordToMinecraftReason: wiadomość, która ma być używana jako powód banowania graczy z serwera Minecraft
# BanSynchronizationMinecraftToDiscord: czy blokować ludzi na serwerze Discord, jeśli zostaną zbanowani na serwerze Minecraft
#
BanSynchronizationDiscordToMinecraft: false
BanSynchronizationDiscordToMinecraftReason: "&cZostałeś zbanowany do odwołania z serwera, ponieważ zostałeś zbanowany na naszym serwerze Discord."
BanSynchronizationMinecraftToDiscord: false
`

2021-05-04 20:32 UTC, Vankka commented
@Zabujca997 Are you planning on continuing this? Config, linking and voice files as well as the LangUtil messages are still missing here

2021-05-05 07:54 UTC, Zabujca997 commented
> @Zabujca997 Are you planning on continuing this? Config, linking and voice files as well as the LangUtil messages are still missing here

Yes, I will continue Polish translate, I forgot to send more files, sorry

2021-05-05 19:51 UTC, Mich3l3k commented
@Zabujca997 Can I help you with translate?

2021-05-05 19:53 UTC, Zabujca997 commented
> @Zabujca997 Can I help you with translate?
> 

Yes write me at Discord Max White#8603

2021-05-05 20:12 UTC, Mich3l3k commented on src/main/resources/messages/pl.yml
> +DiscordChatChannelConsoleCommandNotifyErrorsFormat: "**%user%**, próbowałeś uruchomić polecenie. Niestety wystąpił błąd: %error%"
"**%user%**, próbowałeś/aś uruchomić polecenie. Niestety wystąpił błąd: %error%"

2021-05-05 20:13 UTC, Mich3l3k commented on src/main/resources/messages/pl.yml
> +      Name: "%username% dołączył do serwera"
"%username% dołączył/a do serwera"

2021-05-05 20:24 UTC, Mich3l3k requested changes
voice.yml translate to polish:
```# To jest plik konfiguracyjny modułu głosowego DiscordSRV.
# To funkcja eksperymentalna. Niektóre rzeczy mogą nie działać poprawnie.
# Jeśli bawisz się tym modułem, prześlij nam opinię o wszelkich
# problemach na naszym Discordzie. https://discordsrv.com/discord
#

# Czy włączyć moduł głosowy
Voice enabled: false
# Ilość ticków między aktualizacjami sieci
Tick speed: 5
# Główna kategoria, w której moduł głosowy utworzy / usunie / przeniesie kanały głosowe w
# Żadne kanały inne niż kanał lobby (poniżej) nie powinny znajdować się w tej kategorii
Voice category: 000000000000000000
# Kanał lobby (w kategorii głosowej), do którego ludzie będą przenoszeni, gdy nie będą w zasięgu
# żadnej sieci. Jest to również kanał, do którego ludzie będą przyłączać się,
# aby być podłączonym do zbliżeniowej sieci głosowej.
Lobby channel: 000000000000000000
# Wycisza użytkowników w lobby, którzy mają uprawnienia do mówienia i wyciszania innych w lobby
Mute users who bypass speak permissions in the lobby: true

Network:
  # Maksymalna odległość między graczami w celu połączenia
  Vertical Strength: 40
  Horizontal Strength: 80
  # Gdy gracz dołączył do sieci, może być blokowany
  # przez siłę + spadek bloków dalej, zanim zostanie rozłączony
  Falloff: 5
  # Określa, czy zezwolić na VAD w kanałach głosowych
  Allow voice activation detection: true```

2021-05-05 20:24 UTC, Mich3l3k commented on src/main/resources/messages/pl.yml
> +      Name: "%username% dołączył do serwera po raz pierwszy"
"%username% dołączył/a do serwera po raz pierwszy"

2021-05-05 20:24 UTC, Mich3l3k commented on src/main/resources/messages/pl.yml
> +      Name: "%username% opuścił serwer"
"%username% opuścił/a serwer"

2021-05-05 20:24 UTC, Mich3l3k commented on src/main/resources/messages/pl.yml
> +      Name: "%username% dokonał postępu %achievement%!"
"%username% dokonał/a postępu %achievement%!"

2021-05-05 20:40 UTC, Zabujca997 commented
Alert.yml

```
# To jest / zaawansowana / funkcja DiscordSRV, która umożliwia wysyłanie wiadomości do Discord, gdy nastąpi wydarzenie w grze
# lub gdy polecenie jest uruchamiane. Będziesz potrzebować praktycznej wiedzy o tym, jak działają wydarzenia Bukkit i ich właściwości.
# Jeśli nie jesteś pewien, co tutaj robisz, może zapytaj programistę lub dołącz do naszego serwera pomocy @ discordsrv.com/discord
#
# Zapoznaj się z javadoc interfejsu API Bukkit, aby znaleźć zdarzenia i właściwości do użycia:
#  https://hub.spigotmc.org/javadocs/bukkit
# Pomocne zasoby do nauki używania SpEL:
#  https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/expressions.html
#  https://dzone.com/articles/learn-spring-expression-language-with-examples
#
# Możesz użyć następujących symboli zastępczych:
#  {tps} - server TPS
#  {time} - formatted time
#  {date} - formatted date
#  {name} - if alert is for a player event, the name of the player
#  {ping} - if alert is for a player event, the ping of the player
#  {username} - if alert is for a player event, the username of the player
#  {displayname} - if alert is for a player event, the display name of the player
#  {usernamenoescapes} - if alert is for a player event, the username of the player without escaping discord format (for use in inline code & code block markdown)
#  {displaynamenoescapes} - if alert is for a player event, the display name of the player without escaping discord format (for use in inline code & code block markdown)
#  {world} - if alert is for a player event, the world the player is in
#  {embedavatarurl} - if alert is for a player event, the avatar url for the player's head, otherwise, the bot's avatar url
#  {botavatarurl} - the bot's avatar url
#  {botname} - the bot's name
#  %placeholder% - any PlaceholderAPI placeholders, can only use player ones when alert is for a player event
#
# Możesz także używać wyrażeń SpEL z $ {wyrażenie ...}, takich jak ...
# - Pobieranie adresu IP gracza: $ {# player.address.address.hostAddress}
# - Pobieranie trybu gry gracza: $ {# player.gameMode.name ()}
# - Pobieranie powiązanego identyfikatora konta Discord gracza: $ {# discordsrv.accountLinkManager.getDiscordId (# player.uniqueId)}
# - Pobieranie liczby graczy online: $ {# server.onlinePlayers.size ()}
# - Pobieranie statusu połączenia DiscordSRV z Discord: $ {# jda.status.name ()}
# - Sprawdzanie, czy gracz znajduje się w określonym świecie: $ {# player.world.name == 'world_the_end'}
# - Sprawdzanie, czy na świecie jest dzień, w którym znajduje się gracz: $ {# player.world.time> 0 && # player.world.time <13000}
# Możesz użyć następujących symboli zastępczych wyrażeń, jak widać powyżej:
# #plugins. <plugin> - określona instancja wtyczki, null, jeśli nie istnieje
# #event - zdarzenie, które wyzwala alert, jeśli ten alert jest alertem o zdarzeniu
# #server - instancja serwera API Bukkit, odpowiednik Bukkit # getServer
# #discordsrv - instancja wtyczki DiscordSRV
# #player - gracz, dla którego jest wydarzenie, jeśli jest to wydarzenie lub polecenie gracza
# #sender - nadawca polecenia, jeśli jest to alert polecenia
# #command - pełne polecenie, bez wiodącego ukośnika, jeśli jest to alert dotyczący polecenia
# #args - argumenty polecenia, jeśli jest to alert polecenia
# #allArgs - argumenty polecenia jako jeden ciąg, jeśli jest to alert polecenia
# #channel - kanał docelowy dla tego alertu
# #jda - instancja JDA DiscordSRV, której używa do komunikacji z Discord
#
# Składnia / wartości domyślne:
# - Wyzwalacz: <nazwa zdarzenia lub / polecenie>
# Async: true # opcjonalne, domyślnie true, prawie nigdy nie powinno się tego zmieniać
#    Warunki:
# - właściwość == <> <=> = wartość itp
# Kanał: <nazwa kanału discordsrv>
# IgnoreCancelled: true # tylko dla alertów o zdarzeniach
#    Zawartość: ""
# Webhook:
# Włącz: fałsz
# AvatarUrl: „{botavatarurl}”
# Nazwa: „{nazwa bota}”
# Osadź:
# Włączone: prawda
# Color: „# 00ff00” # akceptuje kod koloru szesnastkowego (np. „#Ffffff”) lub liczbę całkowitą rgb (np. 0)
# Autor:
# ImageUrl: „{embedavatarurl}”
# Nazwa: „{nazwa_użytkownika} zrobił ... coś”.
# Url: „”
# ThumbnailUrl: „”
# Tytuł:
# Tekst: „”
# Url: „”
# Opis: „”
# Pola: [] # format to „tytuł; wartość; inline” (np. „Kto dołączył?;% Displayname%; prawda”) lub „puste”, aby dodać puste pole
# ImageUrl: „”
# Stopka:
# Tekst: „”
# IconUrl: „”
# Timestamp: false # ustawione na true, aby użyć czasu wysłania wiadomości lub użyć znacznika czasu epoki dla określonego czasu (https://www.epochconverter.com/)
#
Alerts:
  # Przykładowa konfiguracja wysyłania wiadomości na kanał DiscordSRV „fish”, gdy graczowi uda się złapać rybę
  #- Trigger: PlayerFishEvent
  #  Channel: fish
  #  Conditions:
  #    - state.name() == 'CAUGHT_FISH'
  #  Embed:
  #    Color: "#00ff00"
  #    Author:
  #      ImageUrl: "{embedavatarurl}"
  #      Name: "{name} caught a ${caught.itemStack.type.name()}!"

  # Przykładowa konfiguracja do wysyłania wiadomości Matrix zapobiegających oszustwom
  #- Trigger: PlayerViolationEvent
  #  Channel: matrix
  #  Conditions:
  #    - violations >= 5 # don't send events for players with < 5 violations
  #  Embed:
  #    Color: "#ff0000"
  #    Author:
  #      ImageUrl: "{embedavatarurl}"
  #      Name: "{username} nie powiodło się ${hackType.name().toLowerCase()} Sprawdź | ${component} | vl:${violations} ping:${player.handle.ping} tps:{tps}"

  # Przykładowa konfiguracja do wysyłania /gamemode wiadomości
  #- Trigger: /gamemode
  #  Channel: gamemode
  #  Conditions:
  #    - '#player.hasPermission("minecraft.command.gamemode") == true'
  #  Embed:
  #    Color: "#ff0000"
  #    Author:
  #      ImageUrl: "{embedavatarurl}"
  #      Name: "{username} changed gamemode to ${#args.get(0)}"

  # Przykładowa konfiguracja do wysyłania poleceń / me
  #- Trigger: /me
  #  Channel: me
  #  Conditions:
  #    - '#player.hasPermission("minecraft.command.me") == true || #player.hasPermission("essentials.me") == true'
  #  Embed:
  #    Color: "#00ff00"
  #    Author:
  #      ImageUrl: "{embedavatarurl}"
  #      Name: "* {username} ${#allArgs}"
```


Linking.yml

```
Require linked account to play:
  Enabled: false

# Jeśli nie wiesz, co to znaczy, nie dotykaj ich
   #
   # Priorytet, na którym powinien być odbiornik złączenia
   # W kolejności od pierwszej do ostatniej dostępne wartości to NAJNIŻSZA, NISKA, NORMALNA, WYSOKA, NAJWYŻSZA
   # Być może będziesz musiał zmienić to na późniejszy priorytet, aby wtyczka banowa wyrzuciła gracza, zanim DiscordSRV ich odmówi
  Listener priority: LOWEST
  # Zdarzenie, w którym moduł łącza powinien nasłuchiwać i nie zezwalać na logowanie
  # Niektóre wtyczki białej listy używają AsyncPlayerPreLoginEvent (dobrze), niektóre używają PlayerLoginEvent (nie tak dobrze)
  Listener event: AsyncPlayerPreLoginEvent
  #
  # Jeśli nie wiesz, co to znaczy, nie dotykaj ich

  # Minecraft IGN, aby zawsze zezwalać na połączenie lub subskrybenta, czy nie
  Bypass names: [Max White, Zabujca997]
  # Czy gracze na białej liście VANILLA omijają potrzebę łączenia swoich kont / mają rolę podrzędną
  Whitelisted players bypass check: true
  # Czy pozwolić graczom na liście banów VANILLA łączyć swoje konta
  Check banned players: true
  # To, czy gracze spoza listy banów VANILLA, ominie potrzebę łączenia ich kont / otrzyma rolę podrzędną
  Only check banned players: false

# Wiadomość do wyrzucenia graczy z poleceniem im powiązania ich kont
   # Użyj {BOT} jako symbolu zastępczego dla nazwy bota
   # Użyj {KOD} jako symbolu zastępczego dla kodu, którego ludzie potrzebują do wysyłania wiadomości DM do bota
   # Użyj {INVITE} jako symbolu zastępczego dla linku z zaproszeniem, które ludzie muszą dołączyć do serwera Discord, używa DiscordInviteLink skonfigurowanego w config.yml
  Not linked message: "&7Musisz połączyć swój &9Discord.\n\n&7Wyślij wiadomość prywatną do &b{BOT}&7 na serwerze Discord zawierającym tylko &b{CODE}&7 aby połączyć swoje konto.\n\n&7Zaproszenie Discord » &b{INVITE}"

  # Jeśli  [...]

2021-05-05 20:42 UTC, Mich3l3k commented
linking.yml
```Require linked account to play:
  Enabled: false

  # Jeśli nie wiesz, co to znaczy, nie dotykaj tego
  #
  # The priority that the join listener should be on
  # Priorytet, na którym powinien być włączony listener złączenia
  # Dostępne wartości to w kolejności od pierwszego do ostatniego: LOWEST, LOW, NORMAL, HIGH, HIGHEST
  # Być może będziesz musiał zmienić to na późniejszy priorytet, aby wtyczka banowa wyrzuciła gracza, zanim DiscordSRV ich zaprzeczy
  Listener priority: LOWEST
  # Zdarzenie, w którym moduł łącza powinien nasłuchiwać i blokować logowanie
  # Niektóre wtyczki białej listy używają AsyncPlayerPreLoginEvent (dobrze), niektóre używają PlayerLoginEvent (nie tak dobrze)
  Listener event: AsyncPlayerPreLoginEvent
  #
  # Jeśli nie wiesz, co to znaczy, nie dotykaj tego

  # IGN Minecrafta, aby zawsze zezwalać na połączenie lub subskrypcję albo nie
  Bypass names: [Scarsz, Vankka]
  # Czy gracze na białej liście VANILLA omijają potrzebę łączenia swoich kont/mają rolę podrzędną
  Whitelisted players bypass check: true
  # Czy pozwolić graczom na liście banów VANILLA łączyć swoje konta
  Check banned players: false
  # Czy gracze spoza listy banów VANILLA, ominie potrzebę łączenia ich kont/otrzyma rolę podrzędną
  Only check banned players: false

  # Kicknięcie gracza z wysłaniem mu wiadomości, żeby połączył swoje konta.
  # Użyj {BOT} jako symbolu zastępczego dla nazwy bota
  # Użyj {CODE} jako symbolu zastępczego dla kodu, którego ludzie potrzebują do wysyłania prywatnych wiadomości do bota
  # Użyj {INVITE} jako symbolu zastępczego dla linku z zaproszeniem, którym muszą dołączyć na serwer discord, używając DiscordInviteLink skonfigurowany w config.yml
  Not linked message: "&7Musisz połączyć swoje konto &9Discord&7a, aby zagrać.\n\n&7Napisz prywatną wiadomość do &b{BOT}&7, który jest na serwerze discord: &b{CODE}&7, aby połączyć swoje konta.\n\n&7Zaproszenie na Discord » &b{INVITE}"

  # Jeśli ta opcja jest włączona, gracze będą musieli nie tylko mieć połączone konta, ale także będą musieli
  # być członkiem serwera Discord, na którym znajduje się również bot.
  #
  # Akceptowalne formaty:
  #   true/false: połączone konto musi znajdować się na co najmniej jednym serwerze Discord, na którym znajduje się również bot
  #     ex: true
  #   <server id>: połączone konto musi znajdować się na danym serwerze Discord
  #     ex: 135634590575493120
  #   [<server id>, <server id>, ...]: połączone konto musi znajdować się na WSZYSTKICH podanych serwerach Discord
  #     ex: [135634590575493120, 690411863766466590]
  #
  # Wartość tej opcji jest zastępowana, jeśli masz role subskrybentów wymuszone poniżej.
  Must be in Discord server: true

  # Opcjonalnie wymagaj, aby ludzie nie tylko byli połączeni, ale także mieli jedną lub wszystkie określone role, takie jak rola podrzędna Twitch
  Subscriber role:
    Require subscriber role to join: false
    Subscriber roles: ["00000000000000000", "00000000000000000", "00000000000000000"]
    Require all of the listed roles: false # jeśli false, tylko tylko jedna rola jest wymagana
    Kick message: "&cMusisz być subksrybentem na Twitch, aby tutaj zagrać."

  Messages:
    DiscordSRV still starting: "&cObecnie nie można sprawdzić statusu łącza, ponieważ serwer nadal łączy się z Discordem.\n\nSpróbuj ponownie za minutę."
    Not in server: "&cObecnie nie jesteś częścią naszego serwera Discord.\n\nDołącz przez {INVITE}!"
    Failed to find subscriber role: "&cNie udało się znaleźć żadnej roli subskrybenta na Discordzie.\n\nSkontaktuj się z administratorami serwera w tej sprawie."
    Failed for unknown reason: "&cWystąpił błąd podczas próby weryfikacji konta.\n\nSkontaktuj się z administratorami serwera w tej sprawie."
    Kicked for unlinking: "&cZostałeś wyrzucony z serwera za rozłączenie kont.\n\nDołącz ponownie do serwera, aby ponownie połączyć swoje konta."```

2021-05-05 20:57 UTC, Zabujca997 reviewed
- Gender types have been improved
- Missing files added

2021-05-06 00:26 UTC, Paidyy commented
"nazwa kanału w grze z Minecrafta" are you sure this translation is correct?

2021-05-06 12:37 UTC, Mich3l3k commented
oh my god
i don't know how i did this mistake

2021-05-06 12:37 UTC, Zabujca997 commented
> "nazwa kanału w grze z Minecrafta" are you sure this translation is correct?

Yes is correct this sentence sounds different for us

2021-05-19 12:35 UTC, Vankka commented
> Missing files added

Some files are still missing, only the `messages` and `synchronization` files have been included in your [`patch-1` branch](https://github.com/Zabujca997/DiscordSRV/tree/patch-1)

2021-05-19 13:12 UTC, Zabujca997 commented
> > Missing files added
> 
> Some files are still missing, only the `messages` and `synchronization` files have been included in your [`patch-1` branch](https://github.com/Zabujca997/DiscordSRV/tree/patch-1)

Sorry, I forgot to add this to [`patch-1` branch](https://github.com/Zabujca997/DiscordSRV/tree/patch-1)

Everything should be fine now: https://github.com/Zabujca997/DiscordSRV/tree/patch-1/src/main/resources

2021-05-19 20:23 UTC, granny requested changes
- The file extension for the linking config should be corrected (Right now it's `pl.uml`, it should be `pl.yml`)
- the voice config needs to have it's option values reverted back to default
- there's a bunch of other nitpicks I have with the other configs

You also still haven't added translations in https://github.com/Zabujca997/DiscordSRV/blob/patch-1/src/main/java/github/scarsz/discordsrv/util/LangUtil.java. Please do so for this PR to be merged.

2021-05-19 20:23 UTC, granny commented on src/main/resources/config/pl.yml
> +Timezone: UTC
```suggestion
# https://github.com/DiscordSRV/DiscordSRV/wiki/config#Timezone
Timezone: default
```

2021-05-19 20:23 UTC, granny commented on src/main/resources/messages/pl.yml
> +DiscordCommandFormat: "&bDołącz do nas na Discordzie przez kod {INVITE}. Aby uzyskać pomoc dotyczącą poleceń, użyj \"/discord ?\""
```suggestion
DiscordCommandFormat: "&bDołącz do nas na Discordzie przez kod {INVITE}&b. Aby uzyskać pomoc dotyczącą poleceń, użyj \"/discord ?\""
```

2021-05-19 20:23 UTC, granny commented on src/main/resources/synchronization/pl.yml
> +# przykład: Jeb_
```suggestion
# %displayname%:            nazwa wyświetlana gracza
#                             example: Jeb
# %username%:               nazwa użytkownika gracza
#                             example: Jeb_
# %discord_name%:           player's discord username
#                             example: Jeb
# %discord_discriminator%:  player's discord discriminator
#                             example: 4988
```
descriptions for `%discord_name%` and `%discord_discriminator%` need to be translated

2021-05-19 20:23 UTC, granny commented on src/main/resources/alerts/pl.yml
> +# Timestamp: false # ustawione na true, aby użyć czasu wysłania wiadomości lub użyć znacznika czasu epoki dla określonego czasu (https://www.epochconverter.com/)
```suggestion
#  - Trigger: <nazwa zdarzenia lub / polecenie>
#    Async: true # opcjonalne, domyślnie true, prawie nigdy nie powinno się tego zmieniać
#    Conditions:
#      - właściwość == <> <=> = wartość itp
#    Channel: <nazwa kanału discordsrv>
#    IgnoreCancelled: true # tylko dla alertów o zdarzeniach
#    Content: ""
#    Webhook:
#      Enable: fałsz
#      AvatarUrl: "{botavatarurl}"
#      Name: "{nazwa bota}"
#    Embed:
#      Enabled: prawda
#      Color: "#00ff00" # akceptuje kod koloru szesnastkowego (np. "#Ffffff") lub liczbę całkowitą rgb (np. 0)
#      Author:
#        ImageUrl: "{embedavatarurl}"
#        Name: "{nazwa_użytkownika} zrobił ... coś".
#        Url: ""
#      ThumbnailUrl: ""
#      Title:
#        Text: ""
#        Url: ""
#      Description: ""
#      Fields: [] # format to "tytuł; wartość; inline" (np. "Kto dołączył?;% Displayname%; prawda") lub "puste", aby dodać puste pole
#      ImageUrl: ""
#      Footer:
#        Text: ""
#        IconUrl: ""
#      Timestamp: false # ustawione na true, aby użyć czasu wysłania wiadomości lub użyć znacznika czasu epoki dla określonego czasu (https://www.epochconverter.com/)
```

2021-05-20 13:14 UTC, Zabujca997 commented on src/main/resources/config/pl.yml
> +DiscordInviteLink: "discord.gg/changethisintheconfig.yml"
Thanks I have already changed it

2021-05-20 13:19 UTC, Zabujca997 commented
The entire translation is ready

- [X] Complete

Thanks to everyone for their help

2021-05-20 18:59 UTC, Vankka reviewed
There are some internal messages in the `LangUtil` that will need to be translated, https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/util/LangUtil.java

2021-05-21 12:56 UTC, Zabujca997 commented
> There are some internal messages in the `LangUtil` that will need to be translated, https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/util/LangUtil.java

I translated everything from it, please check if it works

2021-05-21 15:03 UTC, Zabujca997 commented
All in branch-1:
https://github.com/Zabujca997/DiscordSRV/blob/patch-1/src/main/java/github/scarsz/discordsrv/util/LangUtil.java

2021-05-21 16:07 UTC, Vankka commented on src/main/resources/config/pl.yml
> +DiscordChatChannelDiscordFilters: {".*Online players\\(.*": "", ".*\\*\\*No online players\\*\\*.*": ""}
```suggestion
DiscordChatChannelDiscordFilters: {".*Gracze online\\(.*": "", ".*\\*\\*Brak graczy online\\*\\*.*": ""}
```

2021-05-22 10:31 UTC, Zabujca997 commented on src/main/resources/messages/pl.yml
> +# Symbole zastępcze interfejsu API są również obsługiwane
Okay

2021-05-23 06:59 UTC, granny requested changes
These should be the last of the changes required.

2021-05-23 06:59 UTC, granny commented on src/main/resources/config/pl.yml
> +# minimum dla tej wartości to 10
```suggestion
# ServerWatchdogTimeout: czas w sekundach, który musi upłynąć, zanim watchdog podejmie działanie (wykrywanie awarii Spigota używa do tego 60)
#                        minimum dla tej wartości to 10
```

2021-05-23 06:59 UTC, granny commented on src/main/resources/messages/pl.yml
> +# Symbole zastępcze PlaceholderAPI są również obsługiwane
```suggestion
# Dostępne symbole zastępcze:
# %username%:     surowa nazwa użytkownika gracza
#                  przykład: jeb_
# %displayname%:  nazwa wyświetlana na podstawie pseudonimów
#                  przykład: BigBossManJeb
# %usernamenoescapes%:     surowa nazwa użytkownika gracza bez zmiany formatu niezgody (do użytku w kodzie wbudowanym i przecenie bloków kodu)
#                  przykład: jeb_
# %displaynamenoescapes%:  wyświetlaj nazwę z rzeczy takich jak pseudonimy bez ucieczki formatu niezgody (do użytku w kodzie wbudowanym i znaczniku bloku kodu)
#                  przykład: BigBossManJeb
# %message%:      treść wiadomości
#                  przykład: Hello!
# %primarygroup%: nazwa podstawowej grupy użytkownika
# %world%:        nazwa gracza światowego
#                  przykład: świat
# %worldalias%:   alias gracza światowego jest używany przez Multiverse-Core
#                  przykład: Kontynent
# %date%:         aktualna data i godzina
#                  przykład: Sun 1 Jan 15:30:45 PDT 2017
# %channelname%:  nazwa kanału, na którym wiadomość została wysłana, jeśli w ogóle wiadomość została wysłana w kanale
#                  przykład: Global
# Symbole zastępcze PlaceholderAPI są również obsługiwane
```

2021-05-23 06:59 UTC, granny commented on src/main/resources/messages/pl.yml
> +# przykład: jeb_> Witam z serwera!
```suggestion
# Dostępne symbole zastępcze:
# %channelcolor%:    znak koloru odpowiadający kanałowi
#                     przykład: wiadomości z kanału są w kolorze czerwonym, zostanie to zastąpione kolorem czerwonym
# %channelname%:     dosłowna nazwa kanału, zwykle nazwa, którą wewnętrznie widzi tylko serwer
#                     przykład: personel
# %channelnickname%: formalny pseudonim kanału, zwykle nazwa kanału, który widzą gracze
#                     przykład: Personel
# %message%:         wiadomość po przetworzeniu przez DiscordToMinecraftChatMessageFormat / DiscordToMinecraftChatMessageFormatNoRole
#                     przykład: jeb_> Witam z serwera!
```

2021-05-23 06:59 UTC, granny commented on src/main/resources/messages/pl.yml
> +# Symbole zastępcze PlaceholderAPI są również obsługiwane
```suggestion
# Dostępne symbole zastępcze:
# %message%:  treść wiadomości
#              przykład: Hello!
# %name%:     nazwa użytkownika dla wiadomości wysłanej na czacie internetowym Dynmap (może być puste)
#              przykład: Notch
# Symbole zastępcze PlaceholderAPI są również obsługiwane
```

2021-05-23 06:59 UTC, granny commented on src/main/resources/messages/pl.yml
> +# Symbole zastępcze PlaceholderAPI są również obsługiwane
```suggestion
# Dostępne symbole zastępcze:
# %datetime%:  aktualna data i godzina
#               przykład: Sun 1 Jan 15:30:45 PDT 2017
# %level%:    poziom ważności wiadomości
#               przykład: INFO, WARN, ERROR
# %line%:      linia z konsoli
#               przykład: [DiscordSRV] Włączanie DiscordSRV vX.Y
# Symbole zastępcze PlaceholderAPI są również obsługiwane
```

2021-05-23 06:59 UTC, granny commented on src/main/resources/messages/pl.yml
> +# przykład: brak pozwolenia
```suggestion
# %user%:  nazwa użytkownika, który próbował uruchomić polecenie
#           przykład: Notch
# %error%: przyczyna błędu
#           przykład: brak pozwolenia
```

2021-05-23 06:59 UTC, granny commented on src/main/resources/messages/pl.yml
> +# Symbole zastępcze PlaceholderAPI są również obsługiwane
```suggestion
#   Dostępne symbole zastępcze:
#   %username%:     surowa nazwa użytkownika gracza
#   %displayname%:  nazwa wyświetlana na podstawie pseudonimów
#   %primarygroup%: nazwa podstawowej grupy użytkownika
#   %world%:        nazwa gracza światowego
#   %worldalias%:   alias gracza światowego jest używany przez Multiverse-Core
#   Symbole zastępcze PlaceholderAPI są również obsługiwane
```

2021-05-23 06:59 UTC, granny commented on src/main/resources/messages/pl.yml
> +# MinecraftNobodyFound: %target%: dane wejściowe, które nie doprowadziły do znalezienia żadnych wyników
```suggestion
# CodeGenerated:                %code%:         kod wygenerowany dla gracza, z którym ma połączyć swoje konto
#                               %botname%:      nazwa bota na Discordzie
# DiscordAccountLinked:         %name%:         nazwa gracza Minecraft, z którym było połączone konto Discord użytkownika
#                               %displayname%:  nazwa wyświetlana odtwarzacza Minecraft, z którym było połączone konto użytkownika Discord
#                               %uuid%:         identyfikator użytkownika odtwarzacza Minecraft, z którym było połączone konto Discord użytkownika
# DiscordAccountAlreadyLinked:  %uuid%:         identyfikator użytkownika Minecraft połączonego konta Minecraft użytkownika
#                               %username%:     nazwa użytkownika Minecraft połączonego konta Minecraft użytkownika
# DiscordLinkedAccountRequired  %message%:      wiadomość, której użytkownik nie mógł wysłać, ponieważ nie był połączony
# MinecraftAccountLinked:       %id%:           identyfikator niezgody użytkownika Discord, z którym było połączone konto Minecraft użytkownika
#                               %username%:     nazwa niezgody użytkownika Discord, z którym było połączone konto Minecraft użytkownika
# LinkedCommandSuccess:         %name%:         nazwa użytkownika Discord, z którą połączone jest konto Minecraft użytkownika
# UnlinkCommandSuccess:         %name%:         nazwa użytkownika Discord użytkownika Discord, z którym było połączone konto użytkownika Minecraft
# MinecraftNobodyFound:         %target%:       dane wejściowe, które nie doprowadziły do znalezienia żadnych wyników
```

2021-05-23 06:59 UTC, granny commented on src/main/resources/synchronization/pl.yml
> +# GroupRoleSynchronizationCycleCompletely: czy synchronizacje działające na zegarze powinny synchronizować każdego członka w botach Discord Servers
```suggestion
# GroupRoleSynchronizationGroupsAndRolesToSync: są to role / grupy, które chcesz zsynchronizować między Discord i Minecraft
#                                               {"MC_GROUP_NAME": "DISCORD_ROLE_ID"} to format, który należy zastosować przy dodawaniu większej liczby par grupa / rola
#                                               Aby uzyskać identyfikatory ról swojej gildii Discord, uruchom "/discord debug" i spójrz na pierwszą sekcję
# GroupRoleSynchronizationMinecraftIsAuthoritative: czy zmiany grupowe w Minecrafcie zastępują zmiany ról w Discordzie
# GroupRoleSynchronizationOneWay: czy synchronizować tylko w jedną stronę, sposób synchronizacji zależy od wartości
#                                 of GroupRoleSynchronizationMinecraftIsAuthoritative.
# GroupRoleSynchronizationEnableDenyPermission: czy uprawnienia discordsrv.sync.deny są włączone czy nie.
# GroupRoleSynchronizationPrimaryGroupOnly: jeśli prawda, tylko podstawowa grupa gracza jest liczona do synchronizacji,
#                                           w przeciwnym razie synchronizacja grup liczy wszystkie grupy, w których znajduje się gracz, w tym grupy nadrzędne
# GroupRoleSynchronizationOnLink: czy ponownie synchronizować, gdy gracz łączy się
# GroupRoleSynchronizationCycleTime: liczba minut między wielokrotnym uruchamianiem synchronizacji dla wszystkich graczy online
# GroupRoleSynchronizationCycleCompletely: czy synchronizacje działające na zegarze powinny synchronizować każdego członka w botach Discord Servers
```

2021-05-23 13:27 UTC, Zabujca997 reviewed
All change apply

2021-05-23 19:44 UTC, Vankka commented on src/main/resources/alerts/pl.yml
> +# #jda - instancja JDA DiscordSRV, której używa do komunikacji z Discord
```suggestion
#   #plugins.<plugin> - określona instancja wtyczki, null, jeśli nie istnieje
#   #event - zdarzenie, które wyzwala alert, jeśli ten alert jest alertem o zdarzeniu
#   #server - instancja serwera API Bukkit, odpowiednik Bukkit # getServer
#   #discordsrv - instancja wtyczki DiscordSRV
#   #player - gracz, dla którego jest wydarzenie, jeśli jest to wydarzenie lub polecenie gracza
#   #sender - nadawca polecenia, jeśli jest to alert polecenia
#   #command - pełne polecenie, bez wiodącego ukośnika, jeśli jest to alert dotyczący polecenia
#   #args - argumenty polecenia, jeśli jest to alert polecenia
#   #allArgs - argumenty polecenia jako jeden ciąg, jeśli jest to alert polecenia
#   #channel - kanał docelowy dla tego alertu
#   #jda - instancja JDA DiscordSRV, której używa do komunikacji z Discord
```

2021-05-23 19:44 UTC, Vankka approved these changes

2021-05-23 21:48 UTC, granny approved these changes

2021-05-23 21:49 UTC, merged