Group chat channel console command responses
DiscordSRV/DiscordSRV pull request #1096
Opened 2021-04-21 23:00 UTC by Dinty1

This changes the `SingleCommandSender#sendMessage` method to collect responses for 3 ticks before sending a response to the chat channel.

## Why?
When running a command such as `!c entities`,  a number of messages are sent to the chat channel, which causes rate-limiting and blocks up the channel for a good few seconds. This PR aims to at least mitigate a significant portion of that impact by grouping as many of those messages as possible into one single response.

2021-04-21 23:10 UTC, Scarsz commented
The buffer would be better as a StringJoiner with a `\n` delimiter in my opinion

2021-04-22 06:47 UTC, Dinty1 commented
Changed.

2021-04-22 06:50 UTC, Scarsz requested changes

2021-04-22 06:50 UTC, Scarsz commented on src/main/java/github/scarsz/discordsrv/objects/SingleCommandSender.java
> +                if (this.messageBuffer.toString().equalsIgnoreCase("")) return; // There's nothing in the buffer to send, leave it
StringJoiner#length == 0

2021-04-22 06:50 UTC, Scarsz commented on src/main/java/github/scarsz/discordsrv/objects/SingleCommandSender.java
> +            if (DiscordUtil.escapeMarkdown(this.messageBuffer.toString() + "\n" + message).length() > 1998) { // If the message will be too long (allowing for markdown escaping and the newline)
#toString not necessary

2021-04-22 16:17 UTC, Dinty1 commented
Fixed

2021-04-22 18:13 UTC, merged