Add a discordsrv:server_id LuckPerms context
DiscordSRV/DiscordSRV pull request #1179
Opened 2021-07-01 20:06 UTC by Dinty1

Closes #1174 

Tested, works perfectly 😄

2021-07-01 20:41 UTC, Vankka requested changes
Add the context to `estimatePotentialContexts` aswell

2021-07-01 20:45 UTC, Dinty1 commented
Yep just noticed that thanks

2021-07-01 21:55 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/hooks/permissions/LuckPermsHook.java
> +            consumer.accept(CONTEXT_SERVER_ID, guild.getId());
This would not run if the user is not in the 'main guild', seems kind of counter intuitive

2021-07-02 12:29 UTC, Vankka approved these changes

2021-07-04 18:04 UTC, merged