More appropriate watchdog timeout default message.
DiscordSRV/DiscordSRV pull request #1252
Opened 2021-09-13 04:29 UTC by ipaqmaster

Was pretty worried when I saw this @me this afternoon while away from home thinking some sort of temperature warning threshold were met, or any kind of alarming scenario. Instead it was just a plugin on the Survival instance acting up and making the server's gameticks take a while, activating this watchdog message.

Changed to a more appropriate default message.

2021-09-13 04:31 UTC, ipaqmaster commented
See [this](https://www.reddit.com/r/servers/comments/bmmhki/im_scared_i_run_my_server_in_my_house_and_its/) reddit post for a familiar experience to what I had this afternoon.

2021-09-13 04:43 UTC, Scarsz requested changes
The new message isn't the best in my opinion. If it's going to be changed, it should be changed to be clear and concise. Maybe something like `the server hasn't ticked in 30 seconds`

The message needs to be changed for the other languages as well

2021-09-13 05:58 UTC, ipaqmaster commented
I agree, this was a pretty quick change I made in my own copy as well however your suggestion would be a significantly better message already.

2021-09-17 15:41 UTC, Dinty1 commented
May also be worth incorporating #1259 into this PR

2021-09-19 20:20 UTC, closed without merging