Block specified roles from chat channel
DiscordSRV/DiscordSRV pull request #1297
Opened 2021-10-28 18:48 UTC by vaporrrr

Implements #861

2021-11-24 20:39 UTC, Vankka approved these changes

2021-12-02 14:29 UTC, Scarsz requested changes
I feel like this should probably inform the user that their message wasn't being sent to Minecraft. Whether that be a ❌ reaction or simply deleting the message is up for debate, but I'm not a fan of silently ignoring messages.

2021-12-05 13:28 UTC, Dinty1 approved these changes
LGTM

2021-12-05 20:44 UTC, Vankka approved these changes

2021-12-08 17:20 UTC, merged