Allow you to change the online status of the bot (online, idle, invisible and do not disturb)
DiscordSRV/DiscordSRV pull request #1302
Opened 2021-11-11 20:30 UTC by ANutley

2021-11-11 20:37 UTC, Scarsz requested changes

2021-11-11 20:37 UTC, Scarsz commented on src/main/java/github/scarsz/discordsrv/objects/threads/PresenceUpdater.java
> +                OnlineStatus onlineStatus = OnlineStatus.ONLINE;
Assignment should be in a `default` case

2021-11-11 20:37 UTC, Scarsz commented on src/main/java/github/scarsz/discordsrv/objects/threads/PresenceUpdater.java
> +                switch (onlineStatusString) {
No reason for this switch to exist when the configured values are identical to the enum values, Enum#valueOf(name) would be preferred

Having the configured values be the same isn't good either though. Should be something like `dnd` or at least get rid of the `_`'s with something like `do not disturb`

2021-11-11 20:37 UTC, Scarsz commented on src/main/java/github/scarsz/discordsrv/objects/threads/PresenceUpdater.java
> +    private String lastOnlineStatus = null;
Why is this a String? The lastStatus var is a String because it's a message. This is an enum, it should just be stored as the enum.

2021-11-11 20:37 UTC, Scarsz commented on src/main/resources/config/en.yml
> +DiscordOnlineStatus: "ONLINE"
Quotes not necessary for simple string values

2021-11-23 21:32 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/threads/PresenceUpdater.java
> +                        DiscordSRV.debug(Debug.PRESENCE, "Setting presence to \"" + status + "\"" + (onlineStatus != OnlineStatus.ONLINE ? " and online status to \"" + onlineStatusString + "\"" : "")
Hiding that it's changing the status to online is pointless

2021-11-24 20:26 UTC, Vankka approved these changes

2021-11-24 20:29 UTC, merged