Unix Timestamp Placeholders
DiscordSRV/DiscordSRV pull request #1303
Opened 2021-11-12 10:38 UTC by Cale111

This would close #1271

2021-11-12 15:24 UTC, Vankka requested changes
Please use spaces instead of tabs for indentation in the Java files.

Please also add a extra space between the placeholder and it's description in the messages files, and align all of the other placeholder descriptions to match the indentation, eg.

```diff
...
- # %timestamp%:     current time in seconds since UNIX epoch
- # %starttimestamp%:start time in seconds since UNIX epoch
- # %totalplayers%:  total amount of players to ever join the main world
+ # %timestamp%:      current time in seconds since UNIX epoch
+ # %starttimestamp%: start time in seconds since UNIX epoch
+ # %totalplayers%:   total amount of players to ever join the main world
...
```

2021-11-13 21:07 UTC, Vankka commented on src/main/resources/messages/en.yml
> +#               example: 1483313445
This is missing in files besides English

2021-11-13 22:43 UTC, Vankka approved these changes

2021-12-08 17:10 UTC, Dinty1 approved these changes

2021-12-08 17:25 UTC, merged