Develop
DiscordSRV/DiscordSRV pull request #1332
Opened 2021-12-12 14:38 UTC by Guglieee

2021-12-12 16:05 UTC, Guglieee reviewed
Fixed some things

2021-12-12 16:46 UTC, ANutley requested changes

2021-12-12 16:46 UTC, ANutley commented on src/main/java/github/scarsz/discordsrv/util/LangUtil.java
> +            put(Language.IT, "Failed to download URL");
Need to translate this line

2021-12-12 16:46 UTC, ANutley commented on src/main/resources/config/it.yml
> +# DiscordChatChannelRoleAliases: list of role aliases (alternate names for roles to use in Minecraft messages)
Needs to be translated

2021-12-12 17:01 UTC, Guglieee commented on src/main/resources/config/it.yml
> +# DiscordChatChannelRoleAliases: list of role aliases (alternate names for roles to use in Minecraft messages)
Fixed

2021-12-12 17:05 UTC, Guglieee reviewed
Fixed All

2021-12-12 21:51 UTC, Guglieee commented
I think I have translated everything, if while checking you find something untranslated just tell me and I will translate immediately

2021-12-16 21:00 UTC, Vankka requested changes
A few things I noticed listed below

2021-12-17 10:04 UTC, Guglieee commented
I'm going to work this afternoon

2021-12-17 15:48 UTC, Guglieee commented on src/main/resources/messages/it.yml
> +# DiscordToMinecraftMessageReplyFormat: ilFormatoPerIlMessaggioVisualizzatoPerIndicareCheIlMessaggioÈUnaRisposta
Solved, my mistake

2021-12-17 15:49 UTC, Guglieee commented on src/main/java/github/scarsz/discordsrv/util/LangUtil.java
> +                    "\n");
Solved

2021-12-17 15:49 UTC, Guglieee commented on src/main/java/github/scarsz/discordsrv/util/LangUtil.java
> +                    "\n");
OK

2021-12-17 15:50 UTC, Guglieee commented on src/main/java/github/scarsz/discordsrv/util/LangUtil.java
> +            put(Language.IT, "Account collegati salvati in {ms} ms");
My bad

2021-12-17 15:53 UTC, Guglieee reviewed
I've looked at it now too and there are no mistakes (at least I think)

2021-12-17 18:53 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/util/LangUtil.java
> +                    "\n");
> Please move this below the Polish version

The position still needs to be adjusted

2021-12-18 15:45 UTC, Guglieee commented
@Vankka NOW I have moved it
😄

2022-01-04 10:17 UTC, Guglieee commented
So?

2022-08-01 10:47 UTC, granny requested changes
@Guglieee I apologize for the delay.

I've updated the configs and added english translations that were missing since new options have been added. As soon as these translations are done, I will merge this PR. 

Thank you for your patience.

2022-08-01 10:47 UTC, granny commented on src/main/resources/config/it.yml
> +# DiscordConsoleChannelUseCodeBlocks: if the console should be wrapped in code blocks and colored
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +DiscordToMinecraftMessageReplyFormat: " (replying to %name%)"
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +# PlaceholderAPI placeholders are also supported
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +# {name}:     logger name
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +# DiscordConsoleChannelTimestampFormat: The date format that will be used for the {date} and {datetime} placeholders
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +#   PlaceholderAPI placeholders are also supported
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +# PlaceholderAPI placeholders are also supported
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +# No permission message
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +# Unknown command message
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +# Discord Command Message.
needs to be translated

2022-08-01 10:47 UTC, granny commented on src/main/resources/messages/it.yml
> +# AtServerShutdownFormats ONLY supports %totalplayers%, %serverversion%, %timestamp%, & %date% / %time%
needs to be translated

2022-08-01 11:31 UTC, ANutley requested changes
Again, apologies for the delay, but just a few more nitpicks before we can merge this

2022-08-01 11:31 UTC, ANutley commented on src/main/resources/messages/it.yml
> +# PlaceholderAPI placeholders are also supported
Needs to be translated

2022-08-01 11:31 UTC, ANutley commented on src/main/resources/messages/it.yml
> +# Available placeholders for PlayerLeave messages:
Needs to be translated

2022-08-01 11:31 UTC, ANutley commented on src/main/resources/messages/it.yml
> +# Available placeholders for PlayerDeath messages:
Needs to be translated

2022-08-01 11:31 UTC, ANutley commented on src/main/resources/alerts/it.yml
> +#  - Trigger: <event name or /command>
Needs to be translated

2022-08-01 11:31 UTC, ANutley commented on src/main/resources/alerts/it.yml
> +#    IgnoreCancelled: true # only for event alerts
Needs to be translated

2022-08-01 11:31 UTC, ANutley commented on src/main/resources/alerts/it.yml
> +#      Fields: [] # format is "title;value;inline" (eg. "Who joined?;%displayname%;true") or "blank" to add a blank field
Needs to be translated

2022-08-01 11:31 UTC, ANutley commented on src/main/resources/config/it.yml
> +#    PlaceholderAPI placeholders are supported
Needs to be translated

2022-08-01 11:31 UTC, ANutley commented on src/main/resources/config/it.yml
> +#                         example: Notch
Needs to be fully translated

2022-09-19 11:39 UTC, granny commented
Closing since there's been no activity for a while.

2022-09-19 11:39 UTC, closed without merging