AbstractAccountLinkManager.generateCode: set 10^4 to 10^62 possibilities
DiscordSRV/DiscordSRV pull request #1354
Opened 2022-01-17 01:40 UTC by dylhack

2022-01-17 02:02 UTC, dylhack commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/AbstractAccountLinkManager.java
> + *
I hope this isn't bothersome.

2022-01-17 02:40 UTC, morfie78 approved these changes
+1

2022-01-17 05:57 UTC, Scarsz requested changes
Not at all a fan of using potentially ambiguous characters (l, lowercase L vs I, uppercase I) nor lowercase characters in general

2022-01-17 06:19 UTC, dylhack commented
I hope this helps!

2022-01-24 20:56 UTC, dylhack commented
Any further thoughts on this?

2022-02-20 21:35 UTC, Vankka requested changes
Sorry about the delayed review, other than this one comment this looks fine

2022-02-20 21:35 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/FileAccountLinkManager.java
> +        linkCode = linkCode.toUpperCase();
Please move the `toUpperCase` call above the regex, otherwise lowercase characters will not be picked up

2022-02-22 15:49 UTC, dylhack commented
Excellent, thanks for the response! I will get on that as soon as I can.

2022-02-23 20:34 UTC, Scarsz requested changes
Still not really a fan of the ambiguous characters left such as 0 and O

2022-02-23 23:37 UTC, morfie78 commented
As most people copy/paste the generated code, I don't think ambiguity is a problem.

2022-02-23 23:39 UTC, Scarsz commented
> As most people copy/paste the generated code, I don't think ambiguity is a problem.

Not true, especially when the server requires linking to play; the link code is absolutely not copy/pasteable from the kick screen.

2022-02-24 00:10 UTC, morfie78 commented
You have a point.  @dylhack add a regex to change ambiguous chars?

2022-02-24 17:42 UTC, dylhack commented
I must argue and say that O and 0 aren't very alike, especially with Minecraft's typography. I can understand "I" and "l", but zero and O? Can you list off any more ambiguous characters?

![image](https://user-images.githubusercontent.com/27179786/155578290-1d562501-ad89-408e-b937-21ed6e5d58c0.png)

2022-03-08 14:11 UTC, Scarsz requested changes
I'm still really not a fan of having letters in the linking codes. If letters are behind a disabled by default config option, that would be fine. 6 characters seems overkill as well still but that change doesn't concern me as much.

In addition,

- https://github.com/dylhack/DiscordSRV/blob/develop/src/main/java/github/scarsz/discordsrv/objects/managers/link/JdbcAccountLinkManager.java#L367 needs to contain the updated strip pattern

- The message in all languages at https://github.com/dylhack/DiscordSRV/blob/develop/src/main/resources/messages/en.yml#L429 needs to be updated to reflect the new code style, probably just say codes are alphanumeric

2022-09-16 21:41 UTC, closed without merging