Interface-based Slash Commands API
DiscordSRV/DiscordSRV pull request #1431
Opened 2022-07-31 01:40 UTC by Scarsz

Used by implementing `SlashCommandProvider` on a `Plugin` class. Implement methods to provide your plugin's command(s) metadata and accept automatically routed invocations to your command callback.

```java
public class YourPlugin extends JavaPlugin implements SlashCommandProvider {

    @Override
    public Set<CommandData> getSlashCommandData() {
        return new HashSet<>(Arrays.asList(
                new CommandData("ping", "A classic match of ping pong")
        ));
    }

    @Override
    public void handleSlashCommand(SlashCommandEvent event, String commandPath) {
        if (commandPath.equals("ping")) {
            event.reply("Pong!").queue();
        }
    }

}
```

2022-08-05 16:41 UTC, LOOHP commented
The ability to control which guilds to register a command would be nice.

2022-08-11 12:50 UTC, Scarsz commented
> The ability to control which guilds to register a command would be nice.

@LOOHP Implemented

2022-08-11 12:55 UTC, LOOHP commented
> > The ability to control which guilds to register a command would be nice.
> 
> @LOOHP Implemented

Thanks, looks great!

2022-08-11 15:36 UTC, Vankka requested changes

2022-08-11 15:36 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/api/ApiManager.java
> +                            "Slash command for \"/%s\" was not acknowledged by %s's handler! The command will show as failed on Discord until this is fixed!",
```suggestion
                            "Slash command \"/%s\" was not acknowledged by %s's handler! The command will show as failed on Discord until this is fixed!",
```

2022-08-11 15:36 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/api/commands/PluginCommandData.java
> +    CommandData commandData;
The `CommandData` field isn't being used besides in `equals`, this is misleading as users might construct a CommandData object then pass it to PluginCommandData thinking it's details (eg. anything besides name and description) would be used, when that isn't the case.

Alternatively this class could be changed to not extend CommandData and use the field's CommandData instead.

2022-08-11 15:36 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/api/commands/SlashCommand.java
> +    String path();
Example here would be nice, explaining what parts of the command (command + subcommand group + subcommand) are included and how they need to be formatted (separated by slashes)

2022-08-11 15:36 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/api/commands/SlashCommand.java
> +    boolean deferReply() default false;
Should note why deferring might be useful (3? second responding time vs what deferred replies have)

2022-08-11 15:36 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/api/commands/SlashCommandProvider.java
> + * To handle commands, create a method in a {@link SlashCommandProvider} with the {@link SlashCommand} annotation.
Had to lookup what datum means, and doesn't seem too fitting there.

Should note the required parameter for the method when using the annotation

2022-08-11 16:30 UTC, Vankka approved these changes

2022-08-11 16:57 UTC, Scarsz commented
Had to switch from extending `CommandData` to accepting/storing/passing a built `CommandData` instance. The intermediary methods on `CommandData` like `#addSubcommands` return `CommandData` instead of `<? extends CommandData>` thus prevent chaining because of type mismatches

2022-08-11 17:01 UTC, Vankka approved these changes

2022-08-11 17:23 UTC, merged