Remove plugin upload feature
DiscordSRV/DiscordSRV pull request #1483
Opened 2022-12-25 01:52 UTC by James-Bennett-295

Remove the console channel's plugin upload feature for security reasons.

2022-12-25 01:55 UTC, Scarsz requested changes

2022-12-25 01:55 UTC, Scarsz commented on src/main/java/github/scarsz/discordsrv/listeners/DiscordConsoleListener.java
> -        if (DiscordSRV.isFileSystemLimited()) {
This method should also be removed as no longer needed

2022-12-25 06:52 UTC, Scarsz approved these changes
lgtm

2022-12-25 10:55 UTC, Vankka approved these changes

2022-12-26 22:38 UTC, merged

2022-12-27 10:59 UTC, thewilloftheshadow commented
Not gonna lie, I had no clue this was even a feature