Placeholders for all roles
DiscordSRV/DiscordSRV pull request #1511
Opened 2023-03-04 05:15 UTC by supercoolspy

Adds placeholders for all roles based on #1494 placeholders would end up being:
```
%discordsrv_role_roleid_name% = Cool Role Name
%discordsrv_role_roleid_color_hex% = #FFFFFF
%discordsrv_role_roleid_color_code% = &F&F&F&F&F&F (Converted to color and would not show up as text)
```

2023-03-17 21:57 UTC, supercoolspy commented
@Vankka can you re-run the build? I update from dev

2023-12-24 23:59 UTC, Vankka requested changes
Thank you for your PR and sorry about the late response

I would prefer if the roleId logic was shared for these placeholders, the regular expression could also use a group to catch the role id instead of removing everything besides numbers. Example of what I mean:
```java
private static final Pattern SPECIFIC_ROLE_PATTERN = Pattern.compile("role_(\\d+)_(\\w+)");

Matcher rolePlaceholderMatcher = SPECIFIC_ROLE_PATTERN.matcher(identifier);
if (rolePlaceholderMatcher.matches()) {
    String roleId = rolePlaceholderMatcher.group(1);
    Role role = DiscordUtil.getRole(roleId);
    String subPlaceholder = rolePlaceholderMatcher.group(2);
    
    if (subPlaceholder.equals("name")) {
        ...
    }
}
```

2023-12-24 23:59 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/hooks/PlaceholderAPIExpansion.java
> +        if(identifier.startsWith("role_")) {
```suggestion
        if (identifier.startsWith("role_")) {
```
Styling nitpick

2024-06-27 18:53 UTC, Dinty1 approved these changes
Tested this locally and seems to work perfectly. Only potential barrier to merging is what Vankka said earlier.

2025-01-18 17:05 UTC, Dinty1 approved these changes
LGTM

2025-01-24 07:02 UTC, granny approved these changes

2025-01-24 07:27 UTC, merged