Linked accounts append-only-file backend
DiscordSRV/DiscordSRV pull request #1549
Opened 2023-06-25 23:34 UTC by Scarsz

Closes #1548

2023-06-26 15:33 UTC, Vankka requested changes
Multiple issues regarding if users go manually editing the file, + this breaks compatibility with things that read the .json file

2023-06-26 15:33 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java
> +                        UUID.fromString(matcher.group("uuid"))
This might throw if the file is manually edited

2023-06-26 15:33 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java
> +                UUID uuid = matcher.group("uuid") != null ? UUID.fromString(matcher.group("uuid")) : null;
This might throw if the file is manually edited

2023-06-26 15:33 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java
> +    private static final Pattern MODIFICATION_PATTERN = Pattern.compile("^-(?>(?>(?<discord>\\d+)|(?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})) ?)+$");
The modification pattern doesn't support random crap at the end unlike the link pattern

2023-06-26 15:33 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java
> +    private static final Pattern MODIFICATION_PATTERN = Pattern.compile("^-(?>(?>(?<discord>\\d+)|(?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})) ?)+$");
This also matches >2 different values separated by spaces

2023-06-26 15:33 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java
> +    private static final Pattern MODIFICATION_PATTERN = Pattern.compile("^-(?>(?>(?<discord>\\d+)|(?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})) ?)+$");
```suggestion
    private static final Pattern LINK_PATTERN = Pattern.compile("^(?<discord>\\d+) (?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}).*");
    // matches "-discordId" or "-uuid" or "-discord uuid" or "-uuid discord" https://regex101.com/r/SqriBn
    private static final Pattern MODIFICATION_PATTERN = Pattern.compile("^-(?>(?>(?<discord>\\d+)|(?<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})) ?){1,2}.*");
```

2023-06-26 15:33 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java
> +            }
I think the file shouldn't be deleted for now in case the migration doesn't work properly for whatever reason

2023-06-26 15:38 UTC, Vankka commented
Would be a good idea to log errors for lines that don't match either of the patterns

2023-06-26 15:41 UTC, Scarsz reviewed
> The modification pattern doesn't support random crap at the end unlike the link pattern

I don’t really see that as an issue, the implementation doesn’t add any comments for modification entries because they’ll be deleted later anyway

2023-06-26 15:43 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/objects/managers/link/file/AppendOnlyFileAccountLinkManager.java
> +    // matches "-discordId" or "-uuid" or "-discord uuid" or "-uuid discord" https://regex101.com/r/SqriBn
```suggestion
    // matches "-discordId" or "-uuid" or "-discord uuid" or "-uuid discord" https://regex101.com/r/IkDT4K/
```

2023-06-26 15:49 UTC, Scarsz commented
> this breaks compatibility with things that read the .json file

Not a concern for me, I’ve never been a fan of people reading the file manually. It’s clear that the better method to accomplish those tasks is to use JDBC.

> Would be a good idea to log errors for lines that don't match either of the patterns

I didn’t want to clog up the log any more than it already is if something were to break. That should be rare enough for logging the errors to be fine though.

2023-06-26 15:50 UTC, Vankka commented
> I didn’t want to clog up the log any more than it already is if something were to break. That should be rare enough for logging the errors to be fine though.

Manual user input, if something is misformatted it will get auto-cleared and the user will just be confused that stuff disappeared

2023-06-26 15:53 UTC, Scarsz commented
> > I didn’t want to clog up the log any more than it already is if something were to break. That should be rare enough for logging the errors to be fine though.
> 
> 
> 
> Manual user input, if something is misformatted it will get auto-cleared and the user will just be confused that stuff disappeared

Well, the JSON file would break the entire file if you messed one thing up, lol. Anything’s an improvement over that but I agree we can add a message for it

2023-06-27 08:38 UTC, Vankka approved these changes

2023-07-16 14:57 UTC, merged