v1.27.1
DiscordSRV/DiscordSRV pull request #1629
Opened 2024-01-18 05:04 UTC by granny

2024-07-31 08:55 UTC, Dinty1 approved these changes

2024-08-01 03:36 UTC, Vankka requested changes
Build in unreproducable + a few other in-line comments

2024-08-01 03:36 UTC, Vankka commented on build.gradle.kts
> +    implementation("me.scarsz.jdaappender:jda4:1.2.2-SNAPSHOT")
This snapshot verdion needs to be pinned

2024-08-01 03:36 UTC, Vankka commented on build.gradle.kts
> +    implementation("net.kyori:adventure-platform-bukkit:4.3.4-SNAPSHOT")
This snapshot verdion needs to be pinned

2024-08-01 03:36 UTC, Vankka commented on build.gradle.kts
> +
This snapshot verdion needs to be pinned

2024-08-01 03:36 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/api/commands/PluginSlashCommand.java
> +    }
This should use IJ's auto-generated equals instead of whatever the hell lombok was doing

2024-08-01 03:36 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/api/commands/PluginSlashCommand.java
> +    }
This should use [Objects.hash](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#hash-java.lang.Object...-) instead

2024-08-01 03:36 UTC, Vankka commented on src/main/java/github/scarsz/discordsrv/api/commands/CommandRegistrationError.java
This class really doesn't need a `equals` or ,`hashCode`

2024-08-01 17:49 UTC, Vankka approved these changes

2024-08-03 02:46 UTC, Scarsz approved these changes

2024-08-03 04:44 UTC, merged