Add Translations For pt_BR and pt_PT
DiscordSRV/DiscordSRV pull request #1659
Opened 2024-04-03 00:01 UTC by Joao-Victor-Liporini

hi i make an translation of discordsrv for pt_BR and pt_PT
its possible to merge this pull request?

2024-04-03 01:46 UTC, Scarsz commented
You only translated one message in the `LangUtil` class. The rest of them need to be translated.

2024-04-03 17:08 UTC, Joao-Victor-Liporini commented
> You only translated one message in the `LangUtil` class. The rest of them need to be translated.

sorry, i didn't see that there was more than one message for me, it was just that one, i'll translate the others

2024-04-03 17:35 UTC, Joao-Victor-Liporini commented
well, I think everything's all right now

2024-05-15 09:13 UTC, granny requested changes
I've gone ahead and updated the configs to be more in line with what's updated in the snapshot builds. Please go through my comments and translate all the missing/new sections of text.

2024-05-15 09:13 UTC, granny commented on src/main/resources/alerts/pt.yml
> +#        Name: "{username} did... something."
needs to be translated

2024-05-15 09:13 UTC, granny commented on src/main/resources/alerts/pt.yml
> +  #      Name: "{name} caught a ${caught.itemStack.type.name()}!"
needs to be translated

2024-05-15 09:13 UTC, granny commented on src/main/resources/config/pt.yml
> +# Leave this alone if you don't understand what it does
needs to be translated

2024-05-15 09:13 UTC, granny commented on src/main/resources/config/pt.yml
> +AvatarUrl: ""
needs to be translated

2024-07-08 06:45 UTC, granny requested changes
@Joao-Victor-Liporini there's been some changes to the config files so there's even more to translate. I've gone ahead and updated the configs to be more in line with what's updated in the snapshot builds.

2024-07-08 06:45 UTC, granny commented on src/main/resources/alerts/pt.yml
> +# Made something you'd like to share? You can do so in our Discord server's #alerts forum (invite above)
Needs to be translated.

2024-07-08 06:45 UTC, granny commented on src/main/resources/config/pt.yml
> +# Sets the user status for the bot
Needs to be translated.

2024-07-08 06:45 UTC, granny commented on src/main/resources/config/pt.yml
> +# You can set your own status by not including the prefixes
Needs to be translated.

2024-07-08 06:45 UTC, granny commented on src/main/resources/config/pt.yml
> +    UpdateInterval: 10
Needs to be translated.

2024-07-08 06:45 UTC, granny commented on src/main/resources/synchronization/pt.yml
> +# When a player gets banned on the server when they have a linked Discord account you can optionally ban them on the Discord server and vice versa
Needs to be translated.

2024-07-08 07:01 UTC, granny requested changes
Only just realized you've completely skipped two files. I've also found a few more things that need translations.

2024-07-08 07:01 UTC, granny commented on src/main/resources/synchronization/pt.yml
> +# Requires Vault
Needs to be translated.

2024-07-08 07:01 UTC, granny commented on src/main/resources/synchronization/pt.yml
> +# Can be controlled per player through the use of the 'discordsrv.nicknamesync' permission (granted by default)
Needs to be translated.

2024-07-08 07:01 UTC, granny commented on src/main/resources/messages/pt.yml
This whole file needs to be translated.

2024-07-08 07:01 UTC, granny commented on src/main/resources/linking/pt.yml
This whole file needs to be translated.

2025-04-18 21:43 UTC, granny commented
closing as inactive. Please create a new PR if you decide to contribute translations for pt_BR and pt_PT again.

2025-04-18 21:43 UTC, closed without merging