Develop
DiscordSRV/DiscordSRV pull request #1669
Opened 2024-04-23 00:53 UTC by Ekrem0606

2024-04-23 01:44 UTC, granny requested changes

2024-04-23 01:44 UTC, granny commented on src/main/resources/config/tr.yml
> +ConfigVersion: 1.26.0
```suggestion
ConfigVersion: ${version}
```

2024-04-23 01:44 UTC, granny commented on src/main/resources/config/tr.yml
> +# Oyundan Discord'a kanal bağlantıları
```suggestion
BotToken: "BOTTOKEN"

# The proxy to be used for Discord  
# Leave this alone if you don't understand what it does  
ProxyHost: "https://example.com"  
ProxyPort: 1234  
ProxyUser: "USERNAME"  
ProxyPassword: "PASSWORD"  

# Oyundan Discord'a kanal bağlantıları
```

2024-04-23 01:44 UTC, granny commented on src/main/resources/config/tr.yml
> +AvatarUrl: https://crafatar.com/avatars/{uuid-nodashes}.png?size={size}&overlay#{texture}
```suggestion
AvatarUrl: https://crafthead.net/helm/{uuid-nodashes}/{size}#{texture}
```

2024-04-23 01:44 UTC, granny commented on src/main/resources/config/tr.yml
> +DiscordConsoleChannelBlockBots: false
```suggestion
DiscordConsoleChannelUseCodeBlocks: true
DiscordConsoleChannelBlockBots: true
```

2024-04-23 01:44 UTC, granny commented on src/main/resources/config/tr.yml
> +# DiscordConsoleChannelAllowPluginUpload: Eklentileri konsol kanalına yüklemek onları otomatik olarak sunucuya eklemeli mi?
```suggestion
```

2024-04-23 01:44 UTC, granny commented on src/main/resources/config/tr.yml
> +DiscordChatChannelConsoleCommandRolesAllowed: ["Developer", "Owner"]
```suggestion
DiscordChatChannelConsoleCommandRolesAllowed: ["Owner", "Developer"]
```

2024-04-23 01:44 UTC, granny commented on src/main/resources/config/tr.yml
> +DiscordChatChannelDiscordFilters: {".*Online players\\(.*": "", ".*\\*\\*No online players\\*\\*.*": ""}
```suggestion
DiscordChatChannelDiscordFilters: {".*Online players \\(.*": "", ".*\\*\\*No online players\\*\\*.*": ""}
```

2024-04-23 01:44 UTC, granny commented on src/main/resources/messages/tr.yml
> +ClickToCopyCode: "Click to copy"
```suggestion
# Minecraft
CodeGenerated: "Your link code is %code%. PM the bot on Discord (%botname%) containing just this code as the message to link your accounts."
ClickToCopyCode: "Click to copy"
```

2024-04-23 01:59 UTC, granny requested changes
All the values in the config options need to be translated as well.

2024-04-23 01:59 UTC, granny commented on src/main/resources/config/tr.yml
> +# Leave this alone if you don't understand what it does
needs to be translated

2024-04-23 10:31 UTC, granny requested changes

2024-04-23 10:31 UTC, granny commented on src/main/resources/config/tr.yml
> +    UpdateInterval: 10
Missing translation

2024-04-23 10:31 UTC, granny commented on src/main/resources/config/tr.yml
> +DiscordChatChannelDiscordFilters: {".*Online players \\(.*": "", ".*\\*\\*No online players\\*\\*.*": ""}
Missing translation

2024-04-23 10:31 UTC, granny commented on src/main/resources/config/tr.yml
> +DiscordChatChannelRolesSelection: ["Don't show me!", "Misc role"]
Missing translation

2024-04-23 10:31 UTC, granny commented on src/main/resources/alerts/tr.yml
> +#    Async: true # optional, defaults to true, you should almost never have to change this
Missing translation

2024-04-23 10:31 UTC, granny commented on src/main/resources/alerts/tr.yml
> +#        Name: "{username} did... something."
would be nice if this was translated

2024-04-23 10:31 UTC, granny commented on src/main/resources/alerts/tr.yml
> +#      Fields: [] # format is "title;value;inline" (eg. "Who joined?;%displayname%;true") or "blank" to add a blank field
missing translation

2024-04-23 10:31 UTC, granny commented on src/main/resources/alerts/tr.yml
> +  #      Name: "{name} caught a ${caught.itemStack.type.name()}!"
would be nice if this was translated

2024-04-23 10:31 UTC, granny commented on src/main/resources/alerts/tr.yml
> +  #    - violations >= 5 # don't send events for players with < 5 violations
missing translation

2024-04-23 10:31 UTC, granny commented on src/main/resources/alerts/tr.yml
> +  #      Name: "{username} failed ${hackType.name().toLowerCase()} check | ${component} | vl:${violations} ping:${player.handle.ping} tps:{tps}"
would be nice if this was translated

2024-04-23 10:31 UTC, granny commented on src/main/resources/alerts/tr.yml
> +  #      Name: "{username} changed gamemode to ${#args.get(0)}"
would be nice if this was translated

2024-04-23 19:03 UTC, granny approved these changes
LGTM! @okunamayanad, would be able to review this PR? The more eyes on it the better.

2024-04-23 21:55 UTC, okunamayanad commented
> LGTM! @okunamayanad, would you be able to review this PR? The more eyes on it the better.

It doesn't look good to me, I'm reviewing it but this is going to be a big review

2024-04-23 22:09 UTC, granny commented
> It doesn't look good to me, I'm reviewing it but this is going to be a big review

If you join [the discord server](https://discordsrv.com/discord) I can add you to the ticket that Ekrem0606 created so you can discuss amongst yourselves

2024-04-23 22:34 UTC, okunamayanad requested changes
Part 1/2, will continue tomorrow.
It looks like you used auto translate @Ekrem0606 and it made a lot of errors.

Can you fix these errors?

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +# DiscordChatChannelConsoleCommandNotifyErrors: İzni olmayan bir komutu izinsiz çalıştırmaya çalışan bir kullanıcıya gönderilip gönderilmeyeceği
Auto translate error, explains it incorrectly, should be rewritten

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +# Sohbet kanalı oynatıcı listesi komutu
Auto translate translated "player" incorrectly, use "oyuncu" instead of "oynatıcı"

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +# DiscordChatChannelGameFilters: Discord'a gönderilen sohbet mesajlarına normal ifade filtreleri uygulanacak, sonuç boşsa mesaj hiç gönderilmeyecek
Regex shouldn't be translated for users to search online easily as no one uses "normal ifadeler" to translate "regex"

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +# DiscordChatChannelGameFilters: Discord'a gönderilen sohbet mesajlarına normal ifade filtreleri uygulanacak, sonuç boşsa mesaj hiç gönderilmeyecek
Even the auto translate doesn't translate it at line 258

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +#     %maxmemorygb%:   JVM'nin GB cinsinden maksimum belleği
Maybe make these have the same pattern so its easier to read

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +DiscordCannedResponses: {"!ip": "yourserveripchange.me", "!site": "http://yoursiteurl.net"}
Missing translation

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +# Herhangi bir hazır yanıt istemiyorsanız, bunu yalnızca {}
Non complete sentence, should add "olarak bırakın" to the end

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +# Sunucu gözlemcisi
Auto translate accidentally translated watchdog

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +# Watchdog, sunucunuzun en son ne zaman bir oyun işareti gerçekleştirdiğini sürekli olarak izler
Should probably not translate a game tick into turkish

2024-04-23 22:34 UTC, okunamayanad commented on src/main/resources/config/tr.yml
> +# ServerWatchdogTimeout: Bekçi köpeği harekete geçmeden önce geçmesi gereken saniye cinsinden süre (Spigot'un çarpışma tespiti bunun için 60 kullanır)
Auto translate accidentally translated watchdog

2024-07-01 21:45 UTC, Scarsz commented
Closing due to inactivity

2024-07-01 21:45 UTC, closed without merging