Use the Paper FeedbackCommandSender for Discord to MC commands if it exists
DiscordSRV/DiscordSRV pull request #1724
Opened 2024-07-19 11:26 UTC by sub-kek

I noticed a long time ago that kyori components messages are not sent to discord. I found a simple solution inside Paper Server Implementation.

2024-07-19 11:30 UTC, sub-kek commented
Perhaps we should create a separate class for sendToDiscord(String message) because it is a duplicate of the method from CommandSenderDynamic.

2024-07-21 11:26 UTC, FlingisenFlong approved these changes

2024-07-21 11:26 UTC, Dinty1 requested changes
Seems to work fine. Just a couple of grammar nitpicks

2024-07-21 11:26 UTC, Dinty1 commented on src/main/java/github/scarsz/discordsrv/util/FeedbackCommandSenderUtil.java
> +            plugin.getLogger().severe("Error create commandSender: " + e.getMessage());
```suggestion
            plugin.getLogger().severe("Error creating commandSender: " + e.getMessage());
```

2024-07-21 11:26 UTC, Dinty1 commented on src/main/java/github/scarsz/discordsrv/util/FeedbackCommandSenderUtil.java
> +            plugin.getLogger().severe("Error serialize not relocated component to String: " + e.getMessage());
```suggestion
            plugin.getLogger().severe("Error serializing not relocated component to String: " + e.getMessage());
```

2024-07-21 12:36 UTC, sub-kek commented
Perhaps add a configuration option for this. Since some plugins found only luckperms throws an error when using this sender.

2024-07-21 13:01 UTC, Vankka requested changes
> Perhaps add a configuration option for this. Since some plugins found only luckperms throws an error when using this sender.

Such errors should be reported to the erroring plugins, rather than degrading functionality

2024-07-21 13:06 UTC, sub-kek commented
> Such errors should be reported to the erroring plugins, rather than degrading functionality

Fair enough

2024-07-21 21:46 UTC, closed without merging

2024-07-21 21:51 UTC, granny commented
Why was this closed?

2024-07-21 21:52 UTC, sub-kek commented
> Why was this closed?

Sorry my mistake (force push). Can you reopen this?

2024-07-21 21:54 UTC, Dinty1 commented
Your force push seems to have made it think there are no commits to be pulled. Might be better to make a new one (and ensure you didn’t accidentally wipe other parts of the commit history)

2024-07-21 21:58 UTC, sub-kek commented
> Your force push seems to have made it think there are no commits to be pulled. Might be better to make a new one (and ensure you didn’t accidentally wipe other parts of the commit history)

I know how to fix it anyway I have everything in the local repository.

2024-07-21 21:58 UTC, granny commented
If you force push again it should make it possible to reopen the PR

2024-07-23 16:14 UTC, sub-kek commented
https://github.com/DiscordSRV/DiscordSRV/pull/1727