Full Norwegian Translation
DiscordSRV/DiscordSRV pull request #1743
Opened 2024-08-10 00:27 UTC by RemixedX

Translated every file told to Norwegian

Please credit OPM_Expert because I don't use my GitHub name

2025-01-24 08:28 UTC, granny requested changes
Thanks for the PR, and apologies for the long delay. Some nitpicks since there have been new additions to the config files. Once these are translated, this PR will be merged :)

2025-01-24 08:28 UTC, granny commented on src/main/resources/messages/nb.yml
> +# %userid%:        the ID of the user that is being replied to on Discord
needs to be translated.

2025-01-24 08:28 UTC, granny commented on src/main/resources/messages/nb.yml
> +# MinecraftNobodyFound:         %target%:       the input that led to no results being found
needs to be translated.

2025-01-25 03:15 UTC, RemixedX commented
Only those two?

2025-01-25 04:34 UTC, granny approved these changes
> Only those two?

Yup! Thanks for the PR :)

2025-01-25 04:35 UTC, merged