Add placeholders for user ID
DiscordSRV/DiscordSRV pull request #1755
Opened 2024-08-30 07:17 UTC by fres621

This adds the placeholder `%id%` for and Discord -> Minecraft messages and replies
## Why?
Ideal use case is with MiniMessage's `<insert>` to let Minecraft players ping Discord users without having to grab their ID from the Discord. The following messages.yml config example showcases the use of these new placeholders:
```yml
DiscordToMinecraftChatMessageFormat: '%reply%[<aqua>Discord</aqua> | %toprolecolor%%toprolealias%<reset>] <insert:"<@%id%>">%name%</insert> » %message%'
DiscordToMinecraftChatMessageFormatNoRole: '%reply%[<aqua>Discord</aqua>] <insert:"<@%id%>">%name%</insert> » %message%'
DiscordToMinecraftAllRolesSeparator: ' | '
DiscordToMinecraftMessageReplyFormat: '<insert:"<@%id%>"><hover:show_text:"%name% » %message%">[REPLY]</hover></insert> '
```
Now if you hold shift and click a Discord user's name, their mention will be inserted in the Minecraft chat.
Other possible use cases would be `<click>` tags to run commands that use the user's ID
If translation for these is needed, I'm able to do English and Spanish

2024-09-01 08:23 UTC, Vankka commented
Should be `%userid%` instead

2024-09-01 11:55 UTC, fres621 commented
> Should be `%userid%` instead

Done

2024-09-01 11:57 UTC, Vankka approved these changes

2024-09-01 12:00 UTC, Dinty1 requested changes
This should also be documented in messages.yml with the other placeholders. Just copy-pasting the English across the different files is fine.

2024-09-04 10:24 UTC, fres621 commented
> This should also be documented in messages.yml with the other placeholders. Just copy-pasting the English across the different files is fine.

Done

2024-09-15 11:57 UTC, Dinty1 approved these changes

2024-09-15 11:58 UTC, merged