Fix custom emotes not being translated in webhook messages
DiscordSRV/DiscordSRV pull request #1771
Opened 2024-10-19 21:34 UTC by ANutley

Fixes #1626

2025-01-18 17:02 UTC, Dinty1 requested changes

2025-01-18 17:02 UTC, Dinty1 commented on src/main/java/github/scarsz/discordsrv/util/WebhookUtil.java
> +            chatMessage = DiscordUtil.translateEmotes(message, channel.getGuild());
Should this not be `chatMessage = DiscordUtil.translateEmotes(chatMessage, channel.getGuild());`?

2025-01-18 18:30 UTC, Dinty1 approved these changes

2025-01-24 05:50 UTC, granny approved these changes

2025-01-24 05:51 UTC, merged